const FALLBACK_ANSWER = "المعلومة غير متوفرة ضمن هذه الصفحة.";

const evaluationDataset = [
  {
    id: "field-001",
    category: "field-definition",
    question: "شو يعني Stage؟",
    expectedType: "answer",
    requiredConcepts: [["المرحلة الحالية", "مرحلة"], "المهمة"],
    expectedChunkTerms: ["Stage"],
    expectedFallback: false,
  },
  {
    id: "field-002",
    category: "field-definition",
    question: "شو يعني Appointment From؟",
    expectedType: "answer",
    requiredConcepts: ["Appointment From", ["بداية", "تاريخ بداية"], ["حجز", "موعد"]],
    expectedChunkTerms: ["Appointment From"],
    expectedFallback: false,
  },
  {
    id: "field-003",
    category: "field-definition",
    question: "شو يعني Appointment To؟",
    expectedType: "answer",
    requiredConcepts: ["Appointment To", ["نهاية", "تاريخ نهاية"], ["حجز", "موعد"]],
    expectedChunkTerms: ["Appointment To"],
    expectedFallback: false,
  },
  {
    id: "field-004",
    category: "field-definition",
    question: "شو هو Task Forms؟",
    expectedType: "answer",
    requiredConcepts: ["Task Forms", ["نماذج", "نموذج"], "المهمة"],
    expectedChunkTerms: ["Task Forms"],
    expectedFallback: false,
  },
  {
    id: "field-005",
    category: "field-definition",
    question: "شو نموذج سند التحميل؟",
    expectedType: "answer",
    requiredConcepts: ["سند التحميل", "Task Forms"],
    expectedChunkTerms: ["سند التحميل", "Task Forms"],
    expectedFallback: false,
  },
  {
    id: "field-006",
    category: "field-definition",
    question: "شو هو OTP؟",
    expectedType: "answer",
    requiredConcepts: ["OTP", ["رمز تأكيد", "رمز"], "العميل"],
    expectedChunkTerms: ["OTP"],
    expectedFallback: false,
  },
  {
    id: "compare-001",
    category: "field-comparison",
    question: "شو الفرق بين Assign و Assignees؟",
    expectedType: "answer",
    requiredConcepts: ["Assign", "Assignees", ["المشرف", "متابعة"], ["السائق", "المنفذ"]],
    expectedChunkTerms: ["Assign", "Assignees"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "compare-002",
    category: "field-comparison",
    question: "مين المسؤول عن متابعة المهمة ومين ينفذها؟",
    expectedType: "answer",
    requiredConcepts: ["Assignees", "Assign", ["متابعة", "الإشراف"], ["ينفذ", "المنفذ", "السائق"]],
    expectedChunkTerms: ["Assign", "Assignees"],
    expectedFallback: false,
  },
  {
    id: "compare-003",
    category: "field-comparison",
    question: "الفرق بين المشرف والسائق شو هو؟",
    expectedType: "answer",
    requiredConcepts: [["المشرف", "Assignees"], ["السائق", "Assign"], ["متابعة", "ينفذ"]],
    expectedChunkTerms: ["Assign", "Assignees"],
    expectedFallback: false,
  },
  {
    id: "booking-001",
    category: "appointment-booking",
    question: "متى العميل بيقدر يحجز موعد؟",
    expectedType: "answer",
    requiredConcepts: [["جدولة التوصيل", "رابط حجز"], ["Appointment From", "تاريخ بداية", "بداية"], ["Appointment To", "تاريخ نهايته", "تاريخ نهاية", "نهايته", "نهاية"]],
    expectedChunkTerms: [["Appointment From", "تاريخ بداية", "بداية"], ["Appointment To", "تاريخ نهايته", "تاريخ نهاية", "نهايته", "نهاية"], "حجز"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "booking-002",
    category: "appointment-booking",
    question: "من ايمت لإيمت بقدر احجز؟",
    expectedType: "answer",
    requiredConcepts: [["Appointment From", "بداية"], ["Appointment To", "نهاية"], "حجز"],
    expectedChunkTerms: ["Appointment From", "Appointment To"],
    expectedFallback: false,
  },
  {
    id: "booking-003",
    category: "appointment-booking",
    question: "شو الفترة المسموحة للحجز؟",
    expectedType: "answer",
    requiredConcepts: [["الفترة", "نافذة"], ["Appointment From", "بداية"], ["Appointment To", "نهاية"]],
    expectedChunkTerms: ["Appointment From", "Appointment To"],
    expectedFallback: false,
  },
  {
    id: "booking-004",
    category: "appointment-booking",
    question: "وين بيتحدد وقت الحجز؟",
    expectedType: "answer",
    requiredConcepts: [["Appointment From", "بداية"], ["Appointment To", "نهاية"], ["المهمة", "الحجز"]],
    expectedChunkTerms: ["Appointment From", "Appointment To"],
    expectedFallback: false,
  },
  {
    id: "booking-005",
    category: "appointment-booking",
    question: "العميل فيو يحجز بأي تاريخ؟",
    expectedType: "answer",
    requiredConcepts: [["ضمن", "الفترة"], ["Appointment From", "تاريخ بداية", "بداية"], ["Appointment To", "تاريخ نهايته", "تاريخ نهاية", "نهايته", "نهاية"]],
    expectedChunkTerms: [["Appointment From", "تاريخ بداية", "بداية"], ["Appointment To", "تاريخ نهايته", "تاريخ نهاية", "نهايته", "نهاية"]],
    expectedFallback: false,
  },
  {
    id: "booking-006",
    category: "appointment-booking",
    question: "شو بتعرض شاشة اختيار التاريخ والوقت؟",
    expectedType: "answer",
    requiredConcepts: [["المواعيد المتاحة", "التاريخ والوقت"], ["الفترة", "Appointment"]],
    expectedChunkTerms: ["اختيار التاريخ والوقت", "Appointment"],
    expectedFallback: false,
  },
  {
    id: "workflow-001",
    category: "workflow-sequence",
    question: "اشرحلي من وقت تعيين السائق لحد انتهاء التوصيل",
    expectedType: "answer",
    requiredConcepts: ["Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedSequence: ["تعيين", "Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تعيين السائق", "بوابة السائق", "Completed"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "workflow-full-001",
    category: "workflow-sequence",
    question: "شو تسلسل الخدمات؟",
    expectedType: "answer",
    requiredConcepts: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedSequence: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تسلسل خدمة التوصيل الكامل", "تسلسل الخدمات", "Completed"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "workflow-full-002",
    category: "workflow-sequence",
    question: "شو تسلسل الخدمة؟",
    expectedType: "answer",
    requiredConcepts: ["الفاتورة", "Tasks", "Appointment From", "Appointment To", "Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedSequence: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تسلسل خدمة التوصيل الكامل", "تسلسل الخدمة", "Completed"],
    expectedFallback: false,
  },
  {
    id: "workflow-full-003",
    category: "workflow-sequence",
    question: "شو ترتيب الخطوات؟",
    expectedType: "answer",
    requiredConcepts: ["الفاتورة", "Tasks", "Appointment From", "Appointment To", "Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedSequence: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تسلسل خدمة التوصيل الكامل", "ترتيب الخطوات", "Completed"],
    expectedFallback: false,
  },
  {
    id: "workflow-full-004",
    category: "workflow-sequence",
    question: "شو مراحل الخدمة؟",
    expectedType: "answer",
    requiredConcepts: ["الفاتورة", "Tasks", "Appointment From", "Appointment To", "Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedSequence: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تسلسل خدمة التوصيل الكامل", "مراحل الخدمة", "Completed"],
    expectedFallback: false,
  },
  {
    id: "workflow-full-005",
    category: "workflow-sequence",
    question: "شو دورة الخدمة؟",
    expectedType: "answer",
    requiredConcepts: ["الفاتورة", "Tasks", "Appointment From", "Appointment To", "Task Forms", "Start", "End Task", "OTP", "Completed"],
    expectedSequence: ["الفاتورة", "Tasks", "مهمة التوصيل", "Appointment From", "Appointment To", "جدولة التوصيل", "حجز الموعد", "تعيين السائق", "Task Forms", "بوابة السائق", "Start", "رفع صورة التنفيذ", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تسلسل خدمة التوصيل الكامل", "دورة الخدمة", "Completed"],
    expectedFallback: false,
  },
  {
    id: "workflow-002",
    category: "workflow-sequence",
    question: "شو ترتيب التنفيذ من تعيين السائق للنهاية؟",
    expectedType: "answer",
    requiredConcepts: ["تعيين", "Start", "OTP", "Completed"],
    expectedSequence: ["تعيين", "Start", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["تعيين السائق", "driver-portal-execution"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "workflow-003",
    category: "workflow-sequence",
    question: "شو بصير بعد تعيين السائق؟",
    expectedType: "answer",
    requiredConcepts: ["Task Forms", ["بوابة السائق", "Start"], ["سند التحميل", "نموذج"]],
    expectedChunkTerms: ["Task Forms", "بوابة السائق"],
    expectedFallback: false,
  },
  {
    id: "workflow-004",
    category: "workflow-sequence",
    question: "شو بصير بعد Start؟",
    expectedType: "answer",
    requiredConcepts: [["رفع الصورة", "رفع صورة"], ["End Task", "إنهاء"]],
    expectedSequence: ["Start", "رفع", "End Task"],
    expectedChunkTerms: ["Start", "رفع الصورة"],
    expectedFallback: false,
  },
  {
    id: "workflow-005",
    category: "workflow-sequence",
    question: "شو الخطوة قبل OTP؟",
    expectedType: "answer",
    requiredConcepts: [["End Task", "إنهاء"], "OTP"],
    expectedChunkTerms: ["End Task", "OTP"],
    expectedFallback: false,
  },
  {
    id: "workflow-006",
    category: "workflow-sequence",
    question: "شو الخطوة بعد رفع الصورة؟",
    expectedType: "answer",
    requiredConcepts: [["End Task", "إنهاء المهمة"]],
    expectedChunkTerms: ["رفع الصورة", "End Task"],
    expectedFallback: false,
  },
  {
    id: "workflow-007",
    category: "workflow-sequence",
    question: "متى بتصير المهمة Completed؟",
    expectedType: "answer",
    requiredConcepts: ["Completed", ["OTP", "الرمز"], ["نجاح", "تأكيد"]],
    expectedChunkTerms: ["Completed", "OTP"],
    expectedFallback: false,
  },
  {
    id: "driver-001",
    category: "driver-portal",
    question: "كيف السائق ببلش المهمة؟",
    expectedType: "answer",
    requiredConcepts: [["بوابة السائق", "رابط"], "Start"],
    expectedChunkTerms: ["بوابة السائق", "Start"],
    expectedFallback: false,
  },
  {
    id: "driver-002",
    category: "driver-portal",
    question: "شو بيظهر للسائق بعد بدء المهمة؟",
    expectedType: "answer",
    requiredConcepts: [["رفع الصور", "رفع الصورة"], ["توثيق", "تنفيذ"]],
    expectedChunkTerms: ["رفع الصورة", "بوابة السائق"],
    expectedFallback: false,
  },
  {
    id: "driver-003",
    category: "driver-portal",
    question: "شو بصير بعد End Task؟",
    expectedType: "answer",
    requiredConcepts: ["End Task", "OTP", "Completed"],
    expectedSequence: ["End Task", "OTP", "Completed"],
    expectedChunkTerms: ["End Task", "OTP", "Completed"],
    expectedFallback: false,
    critical: true,
  },
  {
    id: "dialect-001",
    category: "paraphrase-dialect",
    question: "مين المشرف؟",
    expectedType: "answer",
    requiredConcepts: [["Assignees", "المشرف"], ["متابعة", "الإشراف"]],
    expectedChunkTerms: ["Assignees"],
    expectedFallback: false,
  },
  {
    id: "dialect-002",
    category: "paraphrase-dialect",
    question: "مين بينفذ الخدمة؟",
    expectedType: "answer",
    requiredConcepts: [["Assign", "المنفذ"], ["السائق", "ينفذ"]],
    expectedChunkTerms: ["Assign"],
    expectedFallback: false,
  },
  {
    id: "dialect-003",
    category: "paraphrase-dialect",
    question: "مين بيتابع التاسك؟",
    expectedType: "answer",
    requiredConcepts: [["Assignees", "المشرف"], ["متابعة", "التاسك", "المهمة"]],
    expectedChunkTerms: ["Assignees"],
    expectedFallback: false,
  },
  {
    id: "multi-001",
    category: "multi-chunk",
    question: "كيف منحدد الموعد وبعدين شو بيصير مع السائق؟",
    expectedType: "answer",
    requiredConcepts: [["Appointment From", "Appointment To", "حجز"], ["السائق", "Assign"], ["Start", "بوابة"]],
    expectedChunkTerms: ["Appointment", "السائق"],
    expectedFallback: false,
  },
  {
    id: "multi-002",
    category: "multi-chunk",
    question: "وين بشوف الفاتورة والمهمة المرتبطة فيها؟",
    expectedType: "answer",
    requiredConcepts: [["الفاتورة", "Invoice"], ["Tasks", "المهمة"]],
    expectedChunkTerms: ["Invoice", "Tasks"],
    expectedFallback: false,
  },
  {
    id: "term-001",
    category: "terminology-preservation",
    question: "اذكر أسماء الحقول الخاصة بفترة الحجز",
    expectedType: "answer",
    requiredConcepts: ["Appointment From", "Appointment To"],
    expectedChunkTerms: ["Appointment From", "Appointment To"],
    expectedFallback: false,
  },
  {
    id: "term-002",
    category: "terminology-preservation",
    question: "شو الكلمات المهمة ببوابة السائق؟",
    expectedType: "answer",
    requiredConcepts: ["Start", "End Task", "OTP", "Completed"],
    expectedChunkTerms: ["Start", "End Task", "OTP", "Completed"],
    expectedFallback: false,
  },
  {
    id: "boundary-001",
    category: "boundary-ambiguous",
    question: "شو بتعرض هاي الصفحة بشكل عام؟",
    expectedType: "answer",
    requiredConcepts: [["جولة تعريفية", "الشاشات"], ["Odoo", "التوصيل"]],
    expectedChunkTerms: ["جولة", "Odoo"],
    expectedFallback: false,
  },
  {
    id: "boundary-002",
    category: "boundary-ambiguous",
    question: "هل هاي الصفحة بتشرح دورة العمل كاملة؟",
    expectedType: "answer",
    requiredConcepts: [["جولة تعريفية", "تعريفية"], ["لا", "ليست"], ["تنفيذي", "تفصيلي", "دورة العمل"]],
    expectedChunkTerms: ["جولة تعريفية"],
    expectedFallback: false,
  },
  {
    id: "unsupported-001",
    category: "unsupported",
    question: "كيف بعمل مرتجع؟",
    expectedType: "fallback",
    expectedFallback: true,
    critical: true,
  },
  {
    id: "unsupported-002",
    category: "unsupported",
    question: "كيف بعمل صيانة؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-003",
    category: "unsupported",
    question: "كيف بعمل خدمة صيانة؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-004",
    category: "unsupported",
    question: "كيف بعمل تركيب؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-005",
    category: "unsupported",
    question: "كيف بضيف مستخدم جديد؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-006",
    category: "unsupported",
    question: "شو صلاحيات المدير؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-007",
    category: "unsupported",
    question: "شو هو Operation Case؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-008",
    category: "unsupported",
    question: "كيف بغير المستودع؟",
    expectedType: "fallback",
    expectedFallback: true,
  },
  {
    id: "unsupported-009",
    category: "unsupported",
    question: "كيف بعمل Refund؟",
    expectedType: "fallback",
    expectedFallback: true,
    critical: true,
  },
];

module.exports = { FALLBACK_ANSWER, evaluationDataset };
