const FALLBACK_ANSWER = "المعلومة غير متوفرة ضمن هذه الصفحة.";

const globalRagEvaluationDataset = [
  q("global-001", "شو دور SAP و Odoo؟", ["integration-sap-odoo-001"], "confirmed", [], ["SAP", "Odoo", ["المصدر التجاري", "commercial"], ["تشغيل", "operational", "إدارة"]]),
  q("global-002", "مين المصدر التجاري للفواتير؟", ["integration-sap-odoo-001"], "confirmed", [], ["SAP", ["الفواتير", "Invoice"]]),
  q("global-003", "Odoo شو دوره بخدمات ما بعد البيع؟", ["integration-sap-odoo-001", "integration-end-to-end-flow-001"], "confirmed", [], ["Odoo", ["خدمات ما بعد البيع", "After Sales"], ["إدارة", "متابعة", "تشغيل"]]),
  q("global-004", "شو الفلو العام من بيع SAP للتقييم؟", ["integration-end-to-end-flow-001"], "confirmed", [], ["SAP", "Odoo", ["تنفيذ", "execute"], ["تقييم", "Rating"]]),
  q("global-005", "شو الخدمات الموجودة عنا؟", ["overview-after-sales-001"], "confirmed", [], [["التوصيل", "Delivery"], ["التركيب", "Installation"], ["التصنيع", "Manufacturing"], ["القياسات", "Measurement"], ["التصميم", "Design"], ["الصيانة", "Maintenance"]]),
  q("global-006", "هل المشروع مجرد ticketing system؟", ["overview-after-sales-001"], "confirmed", [], [["Operations Management", "إدارة"], ["مو مجرد", "ليس مجرد", "not just"]]),
  q("global-007", "شو مشكلة ربط المنتج بالخدمة؟", ["mapping-product-service-current-issue-001"], "observed", [], ["SAP", "Odoo", ["المنتج", "Product"], ["الخدمة", "Service"], ["يدوي", "manual"]], { statusSensitive: true }),
  q("global-008", "كيف بيرتبط المنتج بالخدمة؟", ["mapping-product-service-requirement-001", "BR-02"], "requirement", [], [["Product", "المنتج"], ["Service", "الخدمة"], ["Mapping", "ربط"]], { statusSensitive: true }),
  q("global-009", "هل النظام بيعرف أي خدمة لأي منتج؟", ["mapping-product-service-current-issue-001", "mapping-product-service-requirement-001", "BR-02"], "requirement", [], [["غير", "تعذر", "مطلوب", "متطلب"], ["SAP", "Odoo"]], { statusSensitive: true }),
  q("global-010", "من وين منعرف الخدمة التابعة لكل منتج؟", ["mapping-product-service-requirement-001", "BR-02"], "requirement", [], ["SAP", ["Mapping", "ربط"], ["Product", "المنتج"]], { statusSensitive: true }),
  q("global-011", "ليش Product-Service Mapping مهم؟", ["mapping-product-service-requirement-001", "BR-02"], "requirement", [], [["أتمتة", "الربط اليدوي", "Mapping"], ["Product", "المنتج"], ["Service", "الخدمة"]]),
  q("global-012", "لو رجع العميل منتج شو بصير بالخدمات؟", ["BR-10", "open-product-service-cancellation-001"], "requirement", [], [["لا يجب", "ما لازم", "ألا يتم", "لا تتأثر", "ألا يؤثر"], ["غير المرتبطة", "غير مرتبطة", "ليست مرتبطة"], ["الخدمة", "Service"]], { statusSensitive: true }),
  q("global-013", "هل Return invoice يلغي كل الخدمات؟", ["BR-10", "open-product-service-cancellation-001"], "requirement", [], [["لا", "ما"], ["كل الخدمات", "جميع خدمات"], ["مرتبطة", "linked"]]),
  q("global-014", "شو Billing Types اللي ظهرت من SAP؟", ["integration-billing-types-001"], "observed", [], ["ZMF2", "ZRE", ["ZS2", "ZS9"]], { statusSensitive: true }),
  q("global-015", "شو يعني ZRE؟", ["integration-billing-types-001"], "observed", [], ["ZRE", ["Return Case", "إرجاع", "مرتجع"]]),
  q("global-016", "شو وضع ZCF2؟", ["integration-zcf2-open-001"], "open", [], ["ZCF2", ["غير محسوم", "لم يتم حسم", "مفتوحة", "open"]], { statusSensitive: true }),
  q("global-017", "هل ZCF2 مؤكد؟", ["integration-zcf2-open-001"], "open", [], ["ZCF2", ["غير", "ليس"], ["محسوم", "مؤكد", "نهائي"]], { statusSensitive: true }),
  q("global-018", "كيف نحدد الفريق من Sales Office؟", ["mapping-sales-office-team-001"], "requirement", [], [["Sales Office"], ["Branch", "فرع"], ["Operational Team", "فريق"]], { statusSensitive: true }),
  q("global-019", "شو وضع mapping المكاتب مثل JED1؟", ["mapping-sales-office-examples-001"], "unconfirmed", [], ["JED1", ["غير مكتمل", "incomplete", "غير مؤكدة", "unconfirmed"]], { statusSensitive: true }),
  q("global-020", "شو مشكلة No eligible Operational Team؟", ["known-error-operational-team-001"], "observed", [], ["No eligible Operational Team", ["تظهر", "UAT", "اختبار"], ["Warehouse", "مستودع"], ["Service", "خدمة"]]),
  q("global-021", "شو صار بفاتورة INV/2026/00108؟", ["uat-invoice-00108-team-assignment-001"], "historical_test", ["delivery"], ["INV/2026/00108", "R502", ["No Eligible Team", "No eligible"]], { statusSensitive: true }),
  q("global-022", "Delivery Only شو حكمها؟", ["BR-03", "workflow-delivery-only-001"], "requirement", ["delivery"], [["Delivery Only", "التوصيل فقط"], ["بدون", "دون"], ["Installation Validation", "تحقق التركيب"]]),
  q("global-023", "شو الفرق بين Delivery Only و Delivery + Installation؟", ["workflow-delivery-installation-dependency-001", "workflow-delivery-only-001", "BR-04"], "requirement", ["delivery", "installation"], [["Delivery Only"], ["Delivery + Installation"], ["موعد التركيب", "Installation Appointment"]]),
  q("global-024", "هل التوصيل مع التركيب يمشي مثل التوصيل فقط؟", ["workflow-delivery-installation-dependency-001", "BR-04"], "requirement", ["delivery", "installation"], [["لا", "ليس"], ["موعد التركيب", "Installation Appointment"]]),
  q("global-025", "شو معنى رسالة حجز موعد التركيب قبل تحريك التوصيل؟", ["known-error-delivery-installation-appointment-001"], "observed", ["delivery", "installation"], [["delivery task", "التوصيل"], ["installation appointment", "موعد التركيب"], ["UAT", "لوحظ", "رسالة"]], { statusSensitive: true }),
  q("global-026", "موعد التوصيل شو علاقته بالتركيب؟", ["workflow-delivery-installation-dependency-001"], "requirement", ["delivery", "installation"], [["موعد التركيب", "Installation Appointment"], ["التوصيل", "Delivery"]]),
  q("global-027", "السائق وين ينفذ خدمة التوصيل؟", ["workflow-delivery-execution-elements-001", "intro-tour:glossary:driver-portal", "intro-tour:stage:driver-portal-execution"], "confirmed", ["delivery"], [["بوابة السائق", "Driver Portal"]], { expectedSourceType: null }),
  q("global-028", "شو خطوات تنفيذ التوصيل عند السائق؟", ["workflow-delivery-execution-elements-001"], "confirmed", ["delivery"], ["Start", ["صورة", "photo"], "End Task", "OTP", "Completed"]),
  q("global-029", "موعد التركيب شو عناصره؟", ["service-installation-001"], "confirmed", ["installation"], [["Appointment", "موعد"], ["Technician", "فني"], ["Partial", "جزئي"]]),
  q("global-030", "شو يعني تكملة لاحقًا؟", ["workflow-installation-stage-proposed-001", "BR-08", "BR-09"], "proposed", ["installation"], [["تكملة لاحق", "وقت لاحق"], ["Partial", "جزئي"], ["متبقية", "Remaining"]], { statusSensitive: true }),
  q("global-031", "هل تكملة لاحقًا confirmed flow؟", ["workflow-installation-stage-proposed-001"], "proposed", ["installation"], [["مقترح", "proposed"], ["ليس", "غير", "مو"]], { statusSensitive: true }),
  q("global-032", "هل لازم يكون في 30 دقيقة بين مواعيد الفني؟", ["BR-06", "requirement-installation-technician-schedule-001"], "requirement", ["installation"], [["30", "ثلاثين"], ["مطلوب", "يجب", "Requirement", "ينبغي"], ["فني", "Technician"]], { statusSensitive: true }),
  q("global-033", "هل الفني ممكن ينحجز بموعدين بنفس الوقت؟", ["BR-05", "requirement-installation-technician-schedule-001"], "requirement", ["installation"], [["لا", "ما", "not"], ["متداخل", "overlap"], ["فني", "Technician"]], { statusSensitive: true }),
  q("global-034", "شو شرط جاهزية البضاعة قبل التركيب؟", ["requirement-installation-goods-readiness-001", "BR-07"], "requirement", ["installation"], [["جاهزية البضاعة", "Goods Ready"], ["قبل", "before"], ["التركيب", "Installation"]]),
  q("global-035", "إذا البضاعة مو كاملة شو المفروض يصير؟", ["requirement-installation-goods-readiness-001", "BR-08"], "requirement", ["installation"], [["Partial", "جزئي"], ["غير كاملة", "مو كاملة", "غير مكتملة", "عدم اكتمال"], ["جاهز", "Ready"]], { statusSensitive: true }),
  q("global-036", "شو خدمة رفع القياسات؟", ["service-measurement-001"], "confirmed", ["measurement"], [["Measurement", "قياسات"], ["decor_measurement", "manufacturing_measurement"]]),
  q("global-037", "هل في فرق بين قياسات ديكور وقياسات تصنيع؟", ["mapping-measurement-types-001"], "unconfirmed", ["measurement"], [["احتمال", "ممكن", "possible", "غير مؤكد"], ["decor", "manufacturing"]], { statusSensitive: true }),
  q("global-038", "شو التصنيع ضمن after sales؟", ["service-manufacturing-001"], "confirmed", ["manufacturing"], [["Manufacturing", "تصنيع"], ["جاهزة", "ready"], ["بعد البيع", "After"]]),
  q("global-039", "شو العلاقة بين القياس والتصنيع والتوصيل؟", ["workflow-manufacturing-high-level-001", "relationship-service-dependencies-001"], "confirmed", ["manufacturing", "measurement"], [["Measurement", "قياس"], ["Manufacturing", "تصنيع"], ["Delivery", "توصيل"]]),
  q("global-040", "شو خدمة التصميم؟", ["service-design-001", "workflow-design-high-level-001"], "confirmed", ["design"], [["Design", "تصميم"], ["بعد البيع", "after sales", "Customer"]]),
  q("global-041", "هل كل فاتورة تمر بالتصميم والقياس والتصنيع؟", ["workflow-design-high-level-001"], "confirmed", ["design"], [["ليس", "مو", "لا"], ["كل", "every"], ["حسب", "depending", "تعتمد", "يعتمد"]]),
  q("global-042", "شو التحويل الداخلي؟", ["service-internal-transfer-001", "workflow-internal-transfer-readiness-001"], "confirmed", ["internal_transfer"], [["داخلي", "Internal"], ["Warehouse", "مستودع"], ["Delivery", "Installation"]]),
  q("global-043", "شو مثال J504 إلى J521؟", ["uat-internal-transfer-j504-j521-001"], "historical_test", ["internal_transfer"], ["J504", "J521", "INV/2026/00087", ["اختبار", "historical"]], { statusSensitive: true }),
  q("global-044", "هل التحويل الداخلي قاعدة عامة من J504 إلى J521؟", ["uat-internal-transfer-j504-j521-001"], "historical_test", ["internal_transfer"], [["ليس", "مو", "لا"], ["قاعدة عامة", "قاعدة عمل عامة", "universal"], ["اختبار", "historical"]], { statusSensitive: true }),
  q("global-045", "شو وضع الصيانة الميدانية؟", ["workflow-maintenance-conceptual-001", "open-maintenance-detail-rules-001"], "unconfirmed", ["maintenance"], [["غير", "ليست", "unconfirmed", "مفتوحة"], ["تفصيلية", "Business Rules"]], { statusSensitive: true }),
  q("global-046", "هل الصيانة الميدانية مطبقة بالكامل؟", ["open-maintenance-detail-rules-001", "workflow-maintenance-conceptual-001"], "open", ["maintenance"], [["لا", "غير", "ليست"], ["مكتملة", "مفصلة", "محسومة", "يكتمل"]], { statusSensitive: true }),
  q("global-047", "شو أسئلة تقييم العميل؟", ["customer-rating-questions-001"], "confirmed", [], [["مقدم الخدمة", "احترافيته"], ["جودة العمل"], ["الالتزام بالموعد"], ["تجربتك"]]),
  q("global-048", "كيف بيرجع تقييم العميل على Odoo؟", ["customer-rating-odoo-link-001"], "requirement", [], [["Service Record", "Service Task"], ["Odoo"], ["Rating", "تقييم"]], { statusSensitive: true }),
  q("global-049", "شو ممكن الإدارة تقيس من التقييم؟", ["analytics-rating-reporting-001"], "proposed", [], [["تقييم كل خدمة", "الخدمة", "service"], ["فريق", "team"], ["فني", "technician"], ["Customer Satisfaction", "رضا العملاء"]], { statusSensitive: true }),
  q("global-050", "كيف ممكن AI يساعد بالمكالمات والتذاكر؟", ["ai-calls-tickets-analysis-001", "ai-recurring-issue-analysis-001"], "proposed", [], [["AI", "الذكاء الاصطناعي"], ["Calls", "مكالمات"], ["Tickets", "تذاكر"], ["تلخيص", "Summarization", "تصنيف"]], { statusSensitive: true }),
  q("global-051", "WhatsApp reply ممكن يعمل Action؟", ["whatsapp-event-action-001"], "proposed", [], [["WhatsApp"], ["موافق"], ["Confirmed", "confirm", "يؤكد", "تأكيد"], ["Reschedule", "إعادة جدولة", "إعادة الجدولة"]], { statusSensitive: true }),
  q("global-052", "شو أهم Business Rules بالمشروع؟", ["BR-01", "BR-02", "BR-11"], "requirement", [], [["Service Identification", "الخدمات"], ["Product Service", "Product-Service", "المنتج"], ["Operational Team"]]),
  q("global-053", "شو يعني Missing Mapping؟", ["BR-12"], "requirement", [], [["Exception", "استثناء"], ["Mapping"], ["مسؤول", "owner"]]),
  q("global-054", "شو العلاقة الأساسية بين Customer و Rating؟", ["relationship-core-after-sales-chain-001"], "confirmed", [], [["Customer"], ["Service", "الخدمة"], ["Rating", "التقييم"]]),
  q("global-055", "شو شكل target system المقترح؟", ["relationship-target-system-map-001"], "proposed", [], [["SAP"], ["Odoo"], ["After Sales Request"], ["Analytics"], ["AI"]], { statusSensitive: true }),
  q("global-056", "شو يعني Tasks؟", ["intro-tour:glossary:tasks"], "confirmed", [], ["Tasks", ["مهمة التوصيل"], ["الفاتورة"]], { expectedSourceType: "page", category: "page_regression" }),
  q("global-057", "شو تسلسل خدمة التوصيل؟", ["intro-tour:workflow-question:full-delivery-workflow-question"], "confirmed", ["delivery"], ["الفاتورة", "Tasks", "Appointment From", "Completed"], { expectedSourceType: "page", category: "page_regression" }),
  unsupported("unsupported-001", "شو عاصمة اليابان؟"),
  unsupported("unsupported-002", "كم عمر الشمس؟"),
  unsupported("unsupported-003", "كيف أطبخ كبسة؟"),
  unsupported("unsupported-004", "شو سعر الذهب اليوم؟"),
  unsupported("unsupported-005", "مين فاز بكأس العالم 2018؟"),
  unsupported("unsupported-006", "كيف أتعلم العزف على البيانو؟"),
  unsupported("unsupported-007", "ما هي سرعة الضوء؟"),
  unsupported("unsupported-008", "اعطيني وصفة قهوة باردة"),
  unsupported("unsupported-009", "شو أفضل هاتف أشتريه؟"),
  unsupported("unsupported-010", "كيف أحجز رحلة إلى اليابان؟"),
];

function q(id, question, expectedChunkIds, expectedStatus, expectedServices, expectedAnswerTerms, options = {}) {
  return {
    id,
    category: options.category || "global_supported",
    question,
    expectedFallback: false,
    expectedSourceType: Object.prototype.hasOwnProperty.call(options, "expectedSourceType") ? options.expectedSourceType : "global",
    expectedChunkIds,
    expectedStatus,
    expectedServices,
    expectedAnswerTerms,
    statusSensitive: Boolean(options.statusSensitive),
  };
}

function unsupported(id, question) {
  return {
    id,
    category: "unsupported",
    question,
    expectedFallback: true,
    expectedSourceType: null,
    expectedChunkIds: [],
    expectedStatus: null,
    expectedServices: [],
    expectedAnswerTerms: [FALLBACK_ANSWER],
  };
}

module.exports = {
  FALLBACK_ANSWER,
  globalRagEvaluationDataset,
};
