const { defineKnowledgeItems } = require("./itemFactory");

const businessRulesKnowledge = defineKnowledgeItems([
  {
    id: "BR-01",
    type: "business_rule",
    domain: "business_rules",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Service Identification",
    text: "The system must identify the services present on the invoice received from SAP.",
    relatedTerms: ["Service Identification", "SAP Invoice", "الخدمات", "الفاتورة"],
  },
  {
    id: "BR-02",
    type: "business_rule",
    domain: "business_rules",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Product-Service Relationship",
    text: "The system must know which product or invoice line is linked to each service.",
    relatedTerms: ["Product-Service Relationship", "Invoice Line", "Product Line", "Service Line"],
  },
  {
    id: "BR-03",
    type: "business_rule",
    domain: "business_rules",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery Only",
    text: "If the invoice contains Delivery only, the system should allow delivery appointment booking and execution without Installation validation.",
    relatedTerms: ["Delivery Only", "Delivery", "Book Delivery", "Installation Validation"],
  },
  {
    id: "BR-04",
    type: "business_rule",
    domain: "business_rules",
    service: ["delivery", "installation"],
    status: "requirement",
    source: "know.md",
    title: "Delivery plus Installation",
    text: "If the invoice contains Delivery plus Installation, required installation path or appointment rules apply before delivery progresses.",
    relatedTerms: ["Delivery + Installation", "Installation Appointment", "Delivery Task", "Validation"],
  },
  {
    id: "BR-05",
    type: "business_rule",
    domain: "business_rules",
    service: ["installation", "maintenance"],
    status: "requirement",
    source: "know.md",
    title: "Technician Conflict",
    text: "The system should not allow booking a technician in overlapping appointments.",
    relatedTerms: ["Technician", "Appointment", "Conflict", "موعد الفني"],
  },
  {
    id: "BR-06",
    type: "business_rule",
    domain: "business_rules",
    service: ["installation", "maintenance"],
    status: "requirement",
    source: "know.md",
    title: "Travel Buffer",
    text: "A time buffer should exist between technician appointments; the example discussed was 30 minutes between the end of one appointment and the start of the next.",
    relatedTerms: ["Travel Buffer", "30 minutes", "Technician Appointment", "وقت انتقال"],
  },
  {
    id: "BR-07",
    type: "business_rule",
    domain: "business_rules",
    service: ["delivery", "installation", "manufacturing", "internal_transfer"],
    status: "requirement",
    source: "know.md",
    title: "Product Readiness",
    text: "The system should verify that the required goods are ready before execution according to service type.",
    relatedTerms: ["Product Readiness", "Goods Ready", "جاهزية البضاعة", "Execution"],
  },
  {
    id: "BR-08",
    type: "business_rule",
    domain: "business_rules",
    service: ["installation"],
    status: "requirement",
    source: "know.md",
    title: "Partial Completion",
    text: "The system should allow part of a service to be executed while retaining the remaining quantity, such as 20 meters installed from 30 meters with 10 meters remaining.",
    relatedTerms: ["Partial Completion", "Partial Installation", "تكملة لاحقًا", "Remaining Quantity"],
  },
  {
    id: "BR-09",
    type: "business_rule",
    domain: "business_rules",
    service: ["installation"],
    status: "requirement",
    source: "know.md",
    title: "Follow-up Priority",
    text: "Requests marked for completion later should have higher priority when booking the later completion appointment.",
    relatedTerms: ["Follow-up Priority", "تكملة لاحقًا", "Appointment", "Priority"],
  },
  {
    id: "BR-10",
    type: "business_rule",
    domain: "business_rules",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Returns",
    text: "Returning a product should not affect a service that is not linked to that returned product.",
    relatedTerms: ["Returns", "Return Case", "Product-Service Relationship", "ZRE"],
  },
  {
    id: "BR-11",
    type: "business_rule",
    domain: "business_rules",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Operational Team Assignment",
    text: "Operational Team should be determined by Warehouse plus Service plus Location or Branch rules.",
    relatedTerms: ["Operational Team", "Warehouse", "Service Type", "Branch", "Location"],
  },
  {
    id: "BR-12",
    type: "business_rule",
    domain: "business_rules",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Missing Mapping",
    text: "If no suitable mapping exists, the case should show a clear exception instead of being left without a responsible owner.",
    relatedTerms: ["Missing Mapping", "Exception", "Operational Team", "Sales Office Mapping"],
  },
]);

module.exports = {
  businessRulesKnowledge,
};
