const { defineKnowledgeItems } = require("./itemFactory");

const customerExperienceKnowledge = defineKnowledgeItems([
  {
    id: "customer-rating-flow-001",
    type: "customer_experience",
    domain: "customer_experience",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "Customer rating flow",
    text: "The customer rating mobile web flow is Service Completed, customer receives rating link, four questions, suggestions, submit, and thank you.",
    relatedTerms: ["Customer Rating", "Mobile Web", "Service Completed", "Rating Link", "Thank You"],
  },
  {
    id: "customer-rating-questions-001",
    type: "customer_experience",
    domain: "customer_experience",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "Customer rating questions",
    text: "The final rating questions are: كيف تقيم تعامل مقدم الخدمة واحترافيته؟ كيف تقيم جودة العمل؟ كيف تقيم الالتزام بالموعد؟ كيف تقيم تجربتك بشكل عام مع الخدمة؟",
    relatedTerms: ["Provider Professionalism", "Work Quality", "Appointment Commitment", "Overall Experience", "أسئلة التقييم"],
  },
  {
    id: "customer-rating-odoo-link-001",
    type: "requirement",
    domain: "customer_experience",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Rating should link to service record",
    text: "The rating result should return to Odoo and link to the Service Record, including service task, customer, rating answers, general comment, and final suggestions.",
    relatedTerms: ["Odoo", "Service Record", "Service Task", "Customer", "Rating", "General Comment", "Final Suggestions"],
  },
  {
    id: "analytics-rating-reporting-001",
    type: "analytics",
    domain: "analytics",
    service: [],
    status: "proposed",
    source: "know.md",
    title: "Customer rating reporting possibilities",
    text: "Management could later report rating by service, team, technician, recurring problems, weak branches, and average customer satisfaction.",
    relatedTerms: ["Reports", "Analytics", "Customer Satisfaction", "Team Rating", "Technician Rating", "Recurring Problems"],
  },
  {
    id: "ai-calls-tickets-analysis-001",
    type: "ai_use_case",
    domain: "ai",
    service: [],
    status: "proposed",
    source: "know.md",
    title: "AI over calls, tickets, service history, and ratings",
    text: "A proposed expanded idea is for AI to learn from Odoo calls, tickets, after-sales history, service cases, and ratings to classify, summarize, and build knowledge.",
    relatedTerms: ["AI", "Calls", "Tickets", "After Sales History", "Classification", "Summarization", "Knowledge"],
  },
  {
    id: "ai-recurring-issue-analysis-001",
    type: "ai_use_case",
    domain: "ai",
    service: [],
    status: "proposed",
    source: "know.md",
    title: "AI recurring issue and low rating analysis",
    text: "Potential AI analysis includes identifying the most recurring issue in installation service, why customers give low ratings, and summarizing customer calls into Odoo.",
    relatedTerms: ["Recurring Issue", "Low Rating", "Installation", "Call Summary", "Odoo"],
  },
  {
    id: "whatsapp-event-action-001",
    type: "ai_use_case",
    domain: "whatsapp",
    service: [],
    status: "proposed",
    source: "know.md",
    title: "WhatsApp reply to business action",
    text: "A proposed WhatsApp flow is customer reply, Odoo receives event or message, business rule, and action. For example, موافق could confirm an appointment, while غير مناسب could open rescheduling, depending on the WhatsApp integration used.",
    relatedTerms: ["WhatsApp", "Odoo", "Business Rule", "Confirmed", "Reschedule", "موافق", "غير مناسب"],
  },
]);

module.exports = {
  customerExperienceKnowledge,
};
