const { defineKnowledgeItems } = require("./itemFactory");

const integrationKnowledge = defineKnowledgeItems([
  {
    id: "overview-after-sales-001",
    type: "system_overview",
    domain: "after_sales",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "After-Sales system purpose",
    text: "The After-Sales project is described as an operations management system, not just a ticketing system. It covers invoices, products, services, warehouses, operational teams, appointments, technicians, delivery, installation, manufacturing, measurement, internal transfers, maintenance, customer rating, and tracking for each stage.",
    relatedTerms: ["After Sales", "Odoo", "خدمات ما بعد البيع", "Operations Management", "Tracking"],
  },
  {
    id: "integration-sap-odoo-001",
    type: "system_overview",
    domain: "integration",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "SAP and Odoo roles",
    text: "SAP is the commercial source for customer sales, invoices, products, and services. Odoo is the operational system for creating, managing, and tracking after-sales service execution.",
    relatedTerms: ["SAP", "Odoo", "الفاتورة", "Invoice", "After Sales"],
  },
  {
    id: "integration-end-to-end-flow-001",
    type: "workflow",
    domain: "integration",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "High-level after-sales flow",
    text: "The high-level flow is Customer to SAP sale or invoice, then data moves to Odoo, then Odoo creates and follows after-sales services, operational teams execute the service, the service is closed, and the customer rates the service.",
    relatedTerms: ["Customer", "SAP Sale", "Invoice", "Odoo", "Service Execution", "Customer Rating"],
  },
  {
    id: "integration-sap-invoice-content-001",
    type: "integration",
    domain: "integration",
    service: [],
    status: "confirmed",
    source: "know.md",
    title: "SAP invoice combinations",
    text: "A SAP invoice may contain products only, product plus service, multiple products plus one service, multiple products plus multiple services, Delivery only, Delivery plus Installation, Manufacturing, Measurement, Design, or other combinations.",
    relatedTerms: ["SAP Invoice", "Products", "Services", "Delivery", "Installation", "Manufacturing", "Measurement", "Design"],
  },
  {
    id: "mapping-product-service-current-issue-001",
    type: "mapping",
    domain: "integration",
    service: [],
    status: "observed",
    source: "know.md",
    title: "Product-service relationship gap",
    text: "The source describes a disagreement with the Odoo team: the team indicated service-to-product linking could not be automated because no direct relationship was present in SAP data. The user objected that manual linking should not be required every time.",
    relatedTerms: ["Product-Service Mapping", "SAP", "Odoo", "Direct Relationship", "Manual Linking"],
  },
  {
    id: "mapping-product-service-requirement-001",
    type: "requirement",
    domain: "integration",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Required SAP product-service mapping",
    text: "The required future behavior is a clear integration and data mapping from SAP so Odoo knows which products are linked to which services, such as Product A to Installation, Product B to Delivery plus Installation, and Product C to Manufacturing plus Installation.",
    relatedTerms: ["Product", "Service", "SAP Mapping", "Odoo", "Installation", "Delivery", "Manufacturing"],
  },
  {
    id: "mapping-service-invoice-product-invoice-001",
    type: "mapping",
    domain: "integration",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Service invoice to product invoice relationship",
    text: "When product and service invoices are separate, the system needs to know the relationship from Service Invoice to Original Product Invoice and from Service Line to Product Line.",
    relatedTerms: ["Service Invoice", "Product Invoice", "Service Line", "Product Line", "Original Product Invoice"],
  },
  {
    id: "integration-billing-types-001",
    type: "mapping",
    domain: "integration",
    service: [],
    status: "observed",
    source: "know.md",
    title: "Observed SAP billing types",
    text: "Observed SAP billing type examples include ZMF2 as After Sales Invoice, ZRE as Return Case, and ZS2 or ZS9 as Service Invoice. Billing type may act as a trigger for the type of case Odoo should open.",
    relatedTerms: ["Billing Type", "Char20", "ZMF2", "ZRE", "ZS2", "ZS9", "After Sales Invoice", "Return Case", "Service Invoice"],
  },
  {
    id: "integration-zcf2-open-001",
    type: "open_question",
    domain: "integration",
    service: [],
    status: "open",
    source: "know.md",
    title: "ZCF2 handling is unresolved",
    text: "The meaning and handling of SAP billing type ZCF2 was not finalized in the available project context.",
    relatedTerms: ["ZCF2", "Billing Type", "SAP", "Open Question"],
  },
  {
    id: "mapping-sales-office-team-001",
    type: "mapping",
    domain: "integration",
    service: [],
    status: "requirement",
    source: "know.md",
    title: "Sales office to branch and team mapping",
    text: "SAP fields such as Sales Organization, Distribution Channel, and Sales Office should allow Odoo to identify the responsible branch, After Sales Team, and Operational Team.",
    relatedTerms: ["Sales Organization", "Distribution Channel", "Sales Office", "Branch", "After Sales Team", "Operational Team"],
  },
  {
    id: "mapping-sales-office-examples-001",
    type: "mapping",
    domain: "integration",
    service: [],
    status: "unconfirmed",
    source: "know.md",
    title: "Sales office examples and incomplete mapping",
    text: "Sales Office examples mentioned include RYD1, JED1, DMM1, and PRJ1, with JED1 mapped as an example to Jeddah After Sales Team. The full real Sales Office mapping table remains incomplete.",
    relatedTerms: ["RYD1", "JED1", "DMM1", "PRJ1", "Jeddah After Sales Team", "Sales Office Mapping"],
  },
  {
    id: "system-after-sales-request-model-001",
    type: "system_overview",
    domain: "odoo",
    service: [],
    status: "observed",
    source: "know.md",
    title: "After Sales Request and team models",
    text: "The Odoo module included model or screen names close to after_sales_request and after_sales_team, suggesting a design based on After Sales Request, Service or Tasks, Team, and Execution, with separate models for some services.",
    relatedTerms: ["after_sales_request", "after_sales_team", "Odoo", "Service Task", "Team", "Execution"],
  },
]);

module.exports = {
  integrationKnowledge,
};
