const { defineKnowledgeItems } = require("./itemFactory");

// Planning discussions for the training website (after-sales-training-portal.md). Mostly proposals:
// the approved stage flows are the website pages, so early draft flows are kept as superseded.
const SOURCE = "after-sales-training-portal.md";

const trainingPortalKnowledge = defineKnowledgeItems([
  {
    id: "training-portal-goal-001",
    type: "system_overview",
    domain: "training_portal",
    service: [],
    status: "proposed",
    source: SOURCE,
    title: "هدف موقع التدريب لخدمات ما بعد البيع",
    text: "الهدف بناء موقع HTML تعليمي (After-Sales Odoo Training Portal) يشرح للموظف دورة العميل كاملة داخل Odoo لخدمات ما بعد البيع، وليس مجرد شرح أسماء الخدمات، بحيث يكون أقرب إلى محاكاة مبسطة لـ Odoo مع خطوات تدريبية. الخدمات المشمولة: رفع القياسات، التصميم، التصنيع، التوصيل، التركيب، استلام المنتج (استلام العميل البضاعة من المستودع)، التحويلات الداخلية، الصيانة الميدانية.",
    relatedTerms: ["موقع التدريب", "Training Portal", "دورة العميل", "محاكاة Odoo"],
  },
  {
    id: "training-portal-structure-001",
    type: "system_overview",
    domain: "training_portal",
    service: [],
    status: "proposed",
    source: SOURCE,
    title: "هيكل موقع التدريب المقترح",
    text: "الصفحة الرئيسية «دورة خدمات ما بعد البيع» تعرض مسار العميل: فاتورة العميل ← تحديد الخدمات ← إنشاء المهام ← حجز الموعد ← تنفيذ الخدمة ← إغلاق المهمة ← تقييم العميل، وتحته بطاقات للخدمات. الأقسام الأربعة المقترحة: دورة العميل (الرحلة من الفاتورة حتى الإغلاق)، الخدمات (شرح كل خدمة منفصلة)، السيناريوهات (توصيل فقط، تركيب + توصيل، تركيب جزئي، عدة خدمات)، التدريب (حالات عملية وأسئلة لاختيار الخطوة الصحيحة).",
    relatedTerms: ["هيكل الموقع", "دورة العميل", "الخدمات", "السيناريوهات", "التدريب"],
  },
  {
    id: "training-portal-simulator-001",
    type: "ai_use_case",
    domain: "training_portal",
    service: [],
    status: "proposed",
    source: SOURCE,
    title: "التدريب التفاعلي (محاكي Odoo)",
    text: "مقترح: يعرض الموقع حالة تشبه Odoo، مثل «العميل اشترى سيراميك + خدمة توصيل + خدمة تركيب — ما الخطوة التالية؟» مع خيارات مثل حجز التوصيل أو حجز التركيب أو إغلاق المهمة. عند الاختيار الصحيح تظهر رسالة تأكيد مع القاعدة (Business Rule) التي تبرر الخطوة، وعند الخطأ رسالة توضح لماذا لا يمكن تنفيذ الخطوة.",
    relatedTerms: ["محاكي Odoo", "Training Simulator", "أسئلة تدريبية"],
  },
  {
    id: "training-portal-page-template-001",
    type: "system_overview",
    domain: "training_portal",
    service: [],
    status: "confirmed",
    source: SOURCE,
    title: "قالب صفحة الخدمة في موقع التدريب",
    text: "تمت مناقشة قالب ECBA كامل لكل خدمة (Business Need، Stakeholders، As-Is / To-Be، Requirements، Acceptance Criteria، UAT، Solution Evaluation)، ثم تقرر إبقاء الموقع عمليًا وبسيطًا وإضافة Business Rules فقط. هيكل صفحة الخدمة: الخدمة ← خطوات دورة العميل ← Business Rules ← الحالات الاستثنائية / السيناريوهات، وتُعرض Business Rules بجانب كل مرحلة أو تحتها.",
    relatedTerms: ["قالب الصفحة", "ECBA", "Business Rules", "السيناريوهات"],
  },
  {
    id: "training-portal-delivery-cases-001",
    type: "requirement",
    domain: "training_portal",
    service: ["delivery"],
    status: "requirement",
    source: SOURCE,
    title: "حالات خدمة التوصيل الأربع",
    text: "حسب شيت الحالات، لخدمة التوصيل 4 حالات رئيسية: (1) توصيل فقط: منتج أو منتجات + خدمة توصيل واحدة. (2) توصيل + خدمة أخرى بتسلسل، مثل توصيل ثم تركيب. (3) توصيل + عدة خدمات / أصناف بحالات مختلفة: بعض المنتجات جاهزة وبعضها غير جاهز، وقد يحدث توصيل جزئي. (4) تصنيع + توصيل + تركيب: التوصيل مرحلة ضمن دورة أكبر تبدأ بالتصنيع. جاهزية المنتج تؤثر على المسار (موجود في نقطة التجميع، غير موجود، أو جزئي)، لذلك أول سؤال في الموقع هو نوع دورة التوصيل عند العميل.",
    relatedTerms: ["حالات التوصيل", "توصيل فقط", "توصيل جزئي", "تصنيع + توصيل + تركيب", "جاهزية المنتج"],
  },
  {
    id: "training-portal-delivery-only-invoice-001",
    type: "uat_observation",
    domain: "training_portal",
    service: ["delivery"],
    status: "observed",
    source: SOURCE,
    title: "مثال فاتورة توصيل فقط",
    text: "مثال من فاتورة فعلية: الفاتورة تحتوي على سطر خدمة توصيل فقط، مثل «أجور توصيل الرياض – جنوب الرياض». المسار التعليمي المبدئي لحالة توصيل فقط: فاتورة توصيل ← إنشاء عملية / مهمة التوصيل في Odoo ← فتح مهمة التوصيل ← تنفيذ دورة التوصيل.",
    relatedTerms: ["فاتورة توصيل فقط", "أجور توصيل", "جنوب الرياض", "توصيل فقط"],
  },
  {
    id: "training-portal-rules-general-delivery-001",
    type: "business_rule",
    domain: "training_portal",
    service: ["delivery"],
    status: "proposed",
    source: SOURCE,
    title: "Business Rules مقترحة — عامة والتوصيل",
    text: "قواعد مقترحة وغير معتمدة بعد. عامة: كل Service Line ينشئ الـ Task المناسب؛ بعض الخدمات مرتبطة بتسلسل خدمات أخرى؛ لا يتم إغلاق المهمة إلا بعد إتمام الخدمة. التوصيل: لا يمكن تنفيذ التوصيل إذا كان المنتج غير جاهز؛ يجب أن تكون المهمة مرتبطة بفاتورة العميل؛ يجب تحديد المستودع / نقطة التجميع؛ يجب تعيين فريق تشغيلي مناسب؛ إذا كان جزء من المنتجات جاهزًا يمكن أن تكون الخدمة توصيلًا جزئيًا حسب السيناريو؛ إذا كانت هناك خدمة تركيب مرتبطة يُطبَّق التسلسل المحدد بين التوصيل والتركيب.",
    relatedTerms: ["Business Rules", "قواعد مقترحة", "جاهزية المنتج", "فريق تشغيلي", "توصيل جزئي"],
  },
  {
    id: "training-portal-rules-installation-001",
    type: "business_rule",
    domain: "training_portal",
    service: ["installation"],
    status: "proposed",
    source: SOURCE,
    title: "Business Rules مقترحة — التركيب",
    text: "قواعد مقترحة وغير معتمدة بعد للتركيب: لا يتم تركيب منتج غير جاهز؛ لا يتم إسناد فني إلى موعدين متداخلين؛ يجب وجود وقت انتقال بين المواعيد؛ التركيب الجزئي ينتقل إلى مرحلة «تكملة لاحقًا».",
    relatedTerms: ["Business Rules", "قواعد مقترحة", "مواعيد متداخلة", "وقت انتقال", "تكملة لاحقًا"],
  },
  {
    id: "training-portal-draft-flows-001",
    type: "workflow",
    domain: "training_portal",
    service: ["delivery", "installation", "design"],
    status: "superseded",
    source: SOURCE,
    title: "مسودات مسارات أولية للتوصيل والتركيب والتصميم",
    text: "مسودات من بداية التخطيط، تختلف عن المسارات المعتمدة حاليًا على الموقع. التوصيل (10 خطوات): وصول الفاتورة من SAP، التأكد من خدمة التوصيل، إنشاء Delivery Task، تحديد المستودع، التأكد من الجاهزية، تحديد الفريق التشغيلي، حجز الموعد، جاري التوصيل، إتمام التوصيل، الإغلاق. التركيب: فاتورة، خدمة تركيب، فحص الجاهزية، حجز الموعد، تعيين الفني، جاري التركيب، تركيب جزئي أو كامل، إغلاق، تقييم. التصميم: طلب العميل، مهمة تصميم، حجز موعد، القياسات، التصميم، مراجعة العميل، اعتماد التصميم، إغلاق.",
    relatedTerms: ["مسودة", "مسار أولي"],
  },
]);

module.exports = { trainingPortalKnowledge };
