const { defineKnowledgeItems } = require("./itemFactory");

const uatKnowledge = defineKnowledgeItems([
  {
    id: "known-error-operational-team-001",
    type: "known_error",
    domain: "uat",
    service: [],
    status: "observed",
    source: "know.md",
    title: "No eligible Operational Team configured",
    text: "A UAT issue was observed with the error No eligible Operational Team is configured for this Warehouse and service. The task existed, but Odoo could not assign an eligible team based on Warehouse, Service, and Operational Team configuration.",
    relatedTerms: ["No eligible Operational Team is configured for this Warehouse and service", "Operational Team", "Warehouse", "Service", "UAT"],
  },
  {
    id: "uat-invoice-00108-team-assignment-001",
    type: "uat_observation",
    domain: "uat",
    service: ["delivery"],
    status: "historical_test",
    source: "know.md",
    title: "INV/2026/00108 team assignment failure",
    text: "UAT example INV/2026/00108 - 1 used Delivery service, Warehouse مستودع الأدوات الصحية – الرياض, and SAP Collection Code R502. The result was Hcos Team Assignment equals No Eligible Team.",
    relatedTerms: ["INV/2026/00108", "Delivery", "مستودع الأدوات الصحية – الرياض", "R502", "Hcos Team Assignment", "No Eligible Team"],
  },
  {
    id: "uat-scenario-product-one-service-001",
    type: "uat_scenario",
    domain: "uat",
    service: [],
    status: "historical_test",
    source: "know.md",
    title: "UAT Scenario 1 product plus one service",
    text: "UAT Scenario 1 covered Product plus one service. Service creation succeeded. The historical example references 4213030704 / 8213025276.",
    relatedTerms: ["Scenario 1", "Product + one service", "4213030704", "8213025276", "Service Creation"],
  },
  {
    id: "uat-scenario-multiple-services-001",
    type: "uat_scenario",
    domain: "uat",
    service: ["delivery", "installation"],
    status: "historical_test",
    source: "know.md",
    title: "UAT Scenario 2 multiple services",
    text: "UAT Scenario 2 covered multiple services, specifically Delivery plus Installation, with example 4213030705 / 8213025277. The focus was flow ordering and validation between delivery and installation.",
    relatedTerms: ["Scenario 2", "Delivery + Installation", "4213030705", "8213025277", "Validation"],
  },
  {
    id: "uat-scenario-partial-installation-001",
    type: "uat_scenario",
    domain: "uat",
    service: ["installation"],
    status: "historical_test",
    source: "know.md",
    title: "UAT Scenario 3 partial installation",
    text: "UAT Scenario 3 covered Partial Installation with example 4114207747 / 8114159138. The target was executing part of the service and completing it later.",
    relatedTerms: ["Scenario 3", "Partial Installation", "4114207747", "8114159138", "تكملة لاحقًا"],
  },
  {
    id: "uat-scenario-delivery-only-001",
    type: "uat_scenario",
    domain: "uat",
    service: ["delivery"],
    status: "historical_test",
    source: "know.md",
    title: "UAT Scenario 5 Delivery Only",
    text: "UAT Scenario 5 covered Delivery Only. Multiple invoices were used during testing, including changing targets INV/2026/00111 - 1 and later INV/2026/00123 - 1.",
    relatedTerms: ["Scenario 5", "Delivery Only", "INV/2026/00111", "INV/2026/00123"],
  },
  {
    id: "uat-playwright-automation-001",
    type: "uat_scenario",
    domain: "uat",
    service: ["delivery"],
    status: "observed",
    source: "know.md",
    title: "Playwright UAT automation scope",
    text: "UAT automation was started with Playwright under a project named approximately odoo UAT and test tests/delivery-flow.spec.ts. The initial requested scope was read-only: login, open خدمة التوصيل, search invoice or task, open task, and verify data.",
    relatedTerms: ["Playwright", "odoo UAT", "tests/delivery-flow.spec.ts", "Read Only", "خدمة التوصيل"],
  },
  {
    id: "uat-playwright-errors-001",
    type: "uat_observation",
    domain: "uat",
    service: ["delivery"],
    status: "observed",
    source: "know.md",
    title: "Playwright automation locator issues",
    text: "Automation issues included Project card not found, Task not found, and Strict mode duplicate locator. Some text appeared in multiple places such as search facets and task cards, so locators were adjusted to use Arabic text like خدمة التوصيل and stage طلب توصيل.",
    relatedTerms: ["Project card not found", "Task not found", "Strict mode duplicate locator", "Search facet", "Task card", "طلب توصيل"],
  },
]);

module.exports = {
  uatKnowledge,
};
