const { defineKnowledgeItems } = require("../itemFactory");

const deliveryKnowledge = defineKnowledgeItems([
  {
    id: "service-delivery-001",
    type: "service",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery service scope",
    text: "Delivery is one of the core After-Sales services. If an invoice contains a Delivery service, the system is expected to create a Delivery Task in Odoo.",
    relatedTerms: ["Delivery", "خدمة التوصيل", "Delivery Task", "Odoo"],
  },
  {
    id: "workflow-delivery-only-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery Only flow",
    text: "For a Delivery Only invoice, the user wanted the system to allow booking the delivery appointment directly without installation-specific validation.",
    relatedTerms: ["Delivery Only", "Book Delivery", "Delivery Appointment", "Installation Validation"],
  },
  {
    id: "workflow-delivery-installation-dependency-001",
    type: "workflow",
    domain: "services",
    service: ["delivery", "installation"],
    status: "requirement",
    source: "know.md",
    title: "Delivery plus Installation dependency",
    text: "For invoices containing Delivery plus Installation, delivery should not progress as if it were Delivery Only. The discussed rule was that the installation appointment must be booked before delivery can continue.",
    relatedTerms: ["Delivery + Installation", "Installation Appointment Booked", "Delivery", "Installation"],
  },
  {
    id: "known-error-delivery-installation-appointment-001",
    type: "known_error",
    domain: "uat",
    service: ["delivery", "installation"],
    status: "observed",
    source: "know.md",
    title: "Delivery stage blocked until installation appointment is booked",
    text: "A UAT error was observed: This delivery task cannot change stage until the customer has booked the installation appointment. This indicates validation tying delivery task stage progress to an installation appointment booking.",
    relatedTerms: ["Delivery Task", "Installation Appointment", "Validation", "This delivery task cannot change stage until the customer has booked the installation appointment"],
  },
  {
    id: "workflow-delivery-execution-elements-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery execution elements",
    text: "Delivery execution knowledge includes appointment booking, appointment window, driver assignment, Task Forms, driver portal, Start, photo upload, End Task, OTP, and Completed.",
    relatedTerms: ["Appointment", "Appointment Window", "Driver Assignment", "Task Forms", "Driver Portal", "Start", "Photo Upload", "End Task", "OTP", "Completed"],
  },
  {
    id: "mapping-delivery-team-assignment-001",
    type: "mapping",
    domain: "team_assignment",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery team assignment should be rule-based",
    text: "Delivery operational team assignment should be based on Warehouse plus Service Type plus Branch or Region, for example Riyadh Warehouse plus Delivery to Riyadh Delivery Team. The example is illustrative, not a finalized mapping table.",
    relatedTerms: ["Delivery Team", "Warehouse", "Service Type", "Branch", "Region", "Riyadh Delivery Team"],
  },
]);

module.exports = {
  deliveryKnowledge,
};
