const { defineKnowledgeItems } = require("../itemFactory");

const deliveryKnowledge = defineKnowledgeItems([
  {
    id: "service-delivery-001",
    type: "service",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery service scope",
    text: "Delivery is one of the core After-Sales services. If an invoice contains a Delivery service, the system is expected to create a Delivery Task in Odoo.",
    relatedTerms: ["Delivery", "خدمة التوصيل", "Delivery Task", "Odoo"],
  },
  {
    id: "workflow-delivery-only-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery Only flow",
    text: "For a Delivery Only invoice, the user wanted the system to allow booking the delivery appointment directly without installation-specific validation.",
    relatedTerms: ["Delivery Only", "Book Delivery", "Delivery Appointment", "Installation Validation"],
  },
  {
    id: "workflow-delivery-installation-dependency-001",
    type: "workflow",
    domain: "services",
    service: ["delivery", "installation"],
    status: "requirement",
    source: "know.md",
    title: "Delivery plus Installation dependency",
    text: "For invoices containing Delivery plus Installation, delivery should not progress as if it were Delivery Only. The discussed rule was that the installation appointment must be booked before delivery can continue.",
    relatedTerms: ["Delivery + Installation", "Installation Appointment Booked", "Delivery", "Installation"],
  },
  {
    id: "known-error-delivery-installation-appointment-001",
    type: "known_error",
    domain: "uat",
    service: ["delivery", "installation"],
    status: "observed",
    source: "know.md",
    title: "Delivery stage blocked until installation appointment is booked",
    text: "A UAT error was observed: This delivery task cannot change stage until the customer has booked the installation appointment. This indicates validation tying delivery task stage progress to an installation appointment booking.",
    relatedTerms: ["Delivery Task", "Installation Appointment", "Validation", "This delivery task cannot change stage until the customer has booked the installation appointment"],
  },
  {
    id: "workflow-delivery-execution-elements-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery execution elements",
    text: "Delivery execution knowledge includes appointment booking, appointment window, driver assignment, Task Forms, driver portal, Start, photo upload, End Task, OTP, and Completed.",
    relatedTerms: ["Appointment", "Appointment Window", "Driver Assignment", "Task Forms", "Driver Portal", "Start", "Photo Upload", "End Task", "OTP", "Completed"],
  },
  {
    id: "mapping-delivery-team-assignment-001",
    type: "mapping",
    domain: "team_assignment",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery team assignment should be rule-based",
    text: "Delivery operational team assignment should be based on Warehouse plus Service Type plus Branch or Region, for example Riyadh Warehouse plus Delivery to Riyadh Delivery Team. The example is illustrative, not a finalized mapping table.",
    relatedTerms: ["Delivery Team", "Warehouse", "Service Type", "Branch", "Region", "Riyadh Delivery Team"],
  },
  {
    id: "integration-delivery-sap-to-odoo-001",
    type: "integration",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery invoice transfer from SAP into Odoo",
    text: "According to the Delivery workflow PDF guide, a Delivery invoice is created and issued in SAP first, and then transferred/integrated into Odoo. The Delivery workflow in Odoo only begins once the invoice has arrived and appears there.",
    relatedTerms: ["SAP", "Odoo", "Invoice", "Integration", "انتقال الفاتورة", "فاتورة من SAP"],
  },
  {
    id: "workflow-delivery-request-auto-schedule-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery Request auto-transition to Delivery Schedule",
    text: "According to the Delivery workflow PDF guide, when an invoice arrives in Odoo it is placed first in the Delivery Request (طلب توصيل) stage. It stays there for a set period of time, after which the system automatically moves it to Delivery Schedule (جدولة التوصيل). If the invoice does not move automatically, this may be because it is linked to another service or has an additional related action pending.",
    relatedTerms: ["طلب توصيل", "جدولة التوصيل", "Delivery Request", "Delivery Schedule", "الانتقال الآلي"],
  },
  {
    id: "workflow-delivery-whatsapp-booking-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "WhatsApp appointment booking message",
    text: "According to the Delivery workflow PDF guide, once the invoice moves into Delivery Schedule, the system automatically sends the customer a WhatsApp message containing a link or mechanism to book the delivery appointment. The customer opens it and selects the appointment date and time that suits them.",
    relatedTerms: ["WhatsApp", "رابط الحجز", "حجز موعد التوصيل", "جدولة التوصيل", "Appointment"],
  },
  {
    id: "business-rule-delivery-daily-capacity-001",
    type: "business_rule",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Daily Capacity per showroom or location",
    text: "According to the Delivery workflow PDF guide, a Daily Capacity is defined for each showroom or location, for example 10 delivery invoices per day. Once bookings for a given date reach that capacity, the system automatically closes that date for booking, blocks the customer from selecting the completed date, and requires the customer to choose another available date. This distributes delivery load according to the daily capacity defined per location.",
    relatedTerms: ["Daily Capacity", "الطاقة الاستيعابية اليومية", "صالة", "موقع", "إغلاق التاريخ للحجز", "موعد آخر متاح"],
  },
  {
    id: "workflow-delivery-driver-assignment-steps-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Driver assignment steps",
    text: "According to the Delivery workflow PDF guide, after the customer books the delivery appointment, the invoice moves to the Driver Assignment (ربط الخدمة بالسائق) stage. The person responsible for delivery opens the invoice, reviews the customer's booking details, selects the responsible driver, links the driver to the invoice, and saves the data.",
    relatedTerms: ["ربط الخدمة بالسائق", "Driver Assignment", "فتح الفاتورة", "اختيار السائق", "حفظ البيانات"],
  },
  {
    id: "field-delivery-post-driver-assignment-details-001",
    type: "field",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Details available after driver assignment",
    text: "According to the Delivery workflow PDF guide, once the driver is linked to the invoice, the task exposes the customer's full booking details: delivery date, delivery time, customer data, customer location, invoice details, and driver data.",
    relatedTerms: ["تاريخ التوصيل", "وقت التوصيل", "بيانات العميل", "موقع العميل", "تفاصيل الفاتورة", "بيانات السائق"],
  },
  {
    id: "workflow-delivery-shipment-handoff-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Shipment preparation and handoff to driver",
    text: "According to the Delivery workflow PDF guide, after driver assignment the invoice moves to a preparation stage where it is readied for actual delivery. The responsible person hands the shipment to the driver, and the driver receives the invoice/shipment, loads it onto the vehicle, confirms the delivery data, and begins executing the delivery. This point marks the start of the driver's actual task.",
    relatedTerms: ["تجهيز الشحنة", "تحميل الشحنة على السيارة", "استلام الفاتورة الشحنة", "بدء تنفيذ التوصيل", "مهمة السائق الفعلية"],
  },
  {
    id: "workflow-delivery-driver-trip-start-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Driver login and Trip Start notification",
    text: "According to the Delivery workflow PDF guide, the driver logs into Odoo through a dedicated driver page using a Username and Password, and after confirming the assigned task's data presses Start / Trip Start. Once the trip is started, the system automatically sends the customer a WhatsApp notification that the shipment is now on its way.",
    relatedTerms: ["دخول السائق", "Start", "Trip Start", "بدء الرحلة", "إشعار العميل", "الشحنة في الطريق"],
  },
  {
    id: "workflow-delivery-arrival-proof-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Arrival at customer and proof of delivery",
    text: "According to the Delivery workflow PDF guide, when the driver reaches the customer's location, the driver delivers the shipment to the customer, uploads a photo as proof of delivery from that location, confirms the delivery is complete, and presses End Task / Trip End.",
    relatedTerms: ["الوصول إلى العميل", "تسليم الشحنة", "صورة إثبات التسليم", "End Task", "Trip End", "نهاية الرحلة"],
  },
  {
    id: "workflow-delivery-otp-completion-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "OTP confirmation and delivery completion",
    text: "According to the Delivery workflow PDF guide, after End Task / Trip End, the system automatically sends an OTP to the customer to confirm receipt of the shipment. The customer gives the OTP to the driver, the driver enters it in the system, the system verifies the code, and once verification succeeds the shipment receipt is confirmed, the Delivery service is considered complete, and the delivery trip is closed.",
    relatedTerms: ["OTP", "تأكيد الاستلام", "التحقق من الرمز", "اكتمال خدمة التوصيل", "إغلاق رحلة التوصيل"],
  },
  {
    id: "mapping-delivery-pdf-detail-vs-primary-workflow-001",
    type: "mapping",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "PDF detailed sequence supports, does not replace, the primary 7-stage Delivery workflow",
    text: "The detailed operational sequence documented in the Delivery workflow PDF guide (SAP invoice creation, transfer to Odoo, Delivery Request, automatic transition to Delivery Schedule, WhatsApp booking message, customer appointment booking, Daily Capacity check, Driver Assignment, shipment preparation and handoff, driver login and Trip Start, in-transit customer notification, arrival and delivery with proof photo, Trip End, OTP, confirmed completion) is supporting operational detail for the current primary 7-stage Delivery workflow (فاتورة من SAP، طلب توصيل، جدولة التوصيل، ربط الخدمة بالسائق، ملئ النموذج، جاري التوصيل، استلام الخدمة) shown on the page. It elaborates on what happens inside and between those 7 stages and must not be used to replace or override the primary workflow.",
    relatedTerms: ["دليل المستخدم", "آلية عمل خدمة التوصيل", "تفاصيل مساندة", "المسار الحالي", "7 مراحل", "لا يستبدل الفلو"],
  },
]);

module.exports = {
  deliveryKnowledge,
};
