const { defineKnowledgeItems } = require("../itemFactory");

const deliveryKnowledge = defineKnowledgeItems([
  {
    id: "service-delivery-001",
    type: "service",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery service scope",
    text: "Delivery is one of the core After-Sales services. If an invoice contains a Delivery service, the system creates a Delivery Task in نظام خدمات مابعد البيع.",
    relatedTerms: ["Delivery", "خدمة التوصيل", "Delivery Task", "نظام خدمات مابعد البيع"],
  },
  {
    id: "workflow-delivery-only-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery Only flow",
    text: "For a Delivery Only invoice, the user wanted the system to allow booking the delivery appointment directly without installation-specific validation.",
    relatedTerms: ["Delivery Only", "Book Delivery", "Delivery Appointment", "Installation Validation"],
  },
  {
    id: "workflow-delivery-installation-dependency-001",
    type: "workflow",
    domain: "services",
    service: ["delivery", "installation"],
    status: "requirement",
    source: "know.md",
    title: "Delivery plus Installation dependency",
    text: "For invoices containing Delivery plus Installation, delivery should not progress as if it were Delivery Only. The discussed rule was that the installation appointment must be booked before delivery can continue.",
    relatedTerms: ["Delivery + Installation", "Installation Appointment Booked", "Delivery", "Installation"],
  },
  {
    id: "known-error-delivery-installation-appointment-001",
    type: "known_error",
    domain: "uat",
    service: ["delivery", "installation"],
    status: "observed",
    source: "know.md",
    title: "Delivery stage blocked until installation appointment is booked",
    text: "A UAT error was observed: This delivery task cannot change stage until the customer has booked the installation appointment. This indicates validation tying delivery task stage progress to an installation appointment booking.",
    relatedTerms: ["Delivery Task", "Installation Appointment", "Validation", "This delivery task cannot change stage until the customer has booked the installation appointment"],
  },
  {
    id: "workflow-delivery-execution-elements-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery execution elements",
    text: "Delivery execution knowledge includes appointment selection based on Daily Capacity, driver assignment, ملئ النموذج (سند التحميل), driver portal, Start to begin the trip, proof photo after delivery, End Task, OTP, and Completed. Customer Delivery does not use a predefined customer booking period or window.",
    relatedTerms: ["Appointment", "Daily Capacity", "Driver Assignment", "ملئ النموذج (سند التحميل)", "Task Forms", "Driver Portal", "Start", "Proof of Delivery", "End Task", "OTP", "Completed"],
  },
  {
    id: "mapping-delivery-team-assignment-001",
    type: "mapping",
    domain: "team_assignment",
    service: ["delivery"],
    status: "requirement",
    source: "know.md",
    title: "Delivery team assignment should be rule-based",
    text: "Delivery operational team assignment should be based on Warehouse plus Service Type plus Branch or Region, for example Riyadh Warehouse plus Delivery to Riyadh Delivery Team. The example is illustrative, not a finalized mapping table.",
    relatedTerms: ["Delivery Team", "Warehouse", "Service Type", "Branch", "Region", "Riyadh Delivery Team"],
  },
  {
    id: "integration-delivery-sap-to-odoo-001",
    type: "integration",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery invoice transfer from SAP into the After-Sales system",
    text: "تبدأ دورة خدمة التوصيل بوصول فاتورة من SAP تحتوي على خدمة التوصيل إلى نظام خدمات مابعد البيع. This invoice is the workflow source and starting event, not an execution service stage.",
    relatedTerms: ["SAP", "نظام خدمات مابعد البيع", "Invoice", "Integration", "انتقال الفاتورة", "فاتورة من SAP", "00"],
  },
  {
    id: "workflow-delivery-request-auto-schedule-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Delivery Request transition to Delivery Schedule",
    text: "تظهر الفاتورة في مرحلة طلب التوصيل، ويتم نقلها إلى مرحلة جدولة التوصيل يدويًا بتغيير المرحلة مباشرة أو باستخدام السحب والإفلات (Drag & Drop). The system may also move the task automatically where applicable.",
    relatedTerms: ["طلب توصيل", "جدولة التوصيل", "Delivery Request", "Delivery Schedule", "تغيير المرحلة", "Drag & Drop", "الانتقال الآلي"],
  },
  {
    id: "workflow-delivery-whatsapp-booking-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "WhatsApp appointment booking message",
    text: "Once the task moves into Delivery Schedule, the system sends the customer a message containing a link to set the delivery and handoff appointment. The customer selects an appointment based on the Daily Capacity configured for the showroom or location, reviews their data, selects the delivery location, and confirms the appointment.",
    relatedTerms: ["WhatsApp", "رابط الحجز", "حجز موعد التوصيل", "جدولة التوصيل", "Appointment", "Daily Capacity", "موقع تسليم البضاعة"],
  },
  {
    id: "business-rule-delivery-daily-capacity-001",
    type: "business_rule",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Daily Capacity per showroom or location",
    text: "According to the Delivery workflow PDF guide, a Daily Capacity is defined for each showroom or location, for example 10 delivery invoices per day. Once bookings for a given date reach that capacity, the system automatically closes that date for booking, blocks the customer from selecting the completed date, and requires the customer to choose another available date. This distributes delivery load according to the daily capacity defined per location.",
    relatedTerms: ["Daily Capacity", "الطاقة الاستيعابية اليومية", "صالة", "موقع", "إغلاق التاريخ للحجز", "موعد آخر متاح"],
  },
  {
    id: "workflow-delivery-driver-assignment-steps-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Driver assignment steps",
    text: "According to the Delivery workflow PDF guide, after the customer books the delivery appointment, the invoice moves to the Driver Assignment (ربط الخدمة بالسائق) stage. The person responsible for delivery opens the invoice, reviews the customer's booking details, selects the responsible driver, links the driver to the invoice, and saves the data.",
    relatedTerms: ["ربط الخدمة بالسائق", "Driver Assignment", "فتح الفاتورة", "اختيار السائق", "حفظ البيانات"],
  },
  {
    id: "field-delivery-post-driver-assignment-details-001",
    type: "field",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Details available after driver assignment",
    text: "According to the Delivery workflow PDF guide, once the driver is linked to the invoice, the task exposes the customer's full booking details: delivery date, delivery time, customer data, customer location, invoice details, and driver data.",
    relatedTerms: ["تاريخ التوصيل", "وقت التوصيل", "بيانات العميل", "موقع العميل", "تفاصيل الفاتورة", "بيانات السائق"],
  },
  {
    id: "workflow-delivery-shipment-handoff-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Shipment preparation and handoff to driver",
    text: "After the driver is selected, the task automatically moves to ملئ النموذج (سند التحميل), where the responsible employee completes all loading-order data. After that data is saved, the task moves to جاري التوصيل and a WhatsApp message is sent to the driver to begin the trip.",
    relatedTerms: ["ملئ النموذج (سند التحميل)", "سند التحميل", "أمر التحميل", "الموظف المعني", "جاري التوصيل", "رسالة واتساب", "بدء الرحلة"],
  },
  {
    id: "workflow-delivery-driver-trip-start-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Driver login and Trip Start notification",
    text: "The driver opens the dedicated driver portal in نظام خدمات مابعد البيع and presses Start to begin the Delivery task and trip. Start is not restricted to the moment when the driver reaches the customer. Once the trip is started, the system may send the documented in-transit notification.",
    relatedTerms: ["دخول السائق", "Start", "Trip Start", "بدء الرحلة", "إشعار العميل", "الشحنة في الطريق"],
  },
  {
    id: "workflow-delivery-arrival-proof-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "Arrival at customer and proof of delivery",
    text: "بعد الانتهاء من عملية التوصيل، يقوم السائق برفع صورة لتوثيق إتمام التوصيل، ثم يكمل مسار End Task / Trip End وفق المعرفة الموثقة.",
    relatedTerms: ["توثيق التوصيل", "تسليم الشحنة", "صورة إثبات التسليم", "End Task", "Trip End", "نهاية الرحلة"],
  },
  {
    id: "workflow-delivery-otp-completion-001",
    type: "workflow",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "OTP confirmation and delivery completion",
    text: "According to the Delivery workflow PDF guide, after End Task / Trip End, the system automatically sends an OTP to the customer to confirm receipt of the shipment. The customer gives the OTP to the driver, the driver enters it in the system, the system verifies the code, and once verification succeeds the shipment receipt is confirmed, the Delivery service is considered complete, and the delivery trip is closed.",
    relatedTerms: ["OTP", "تأكيد الاستلام", "التحقق من الرمز", "اكتمال خدمة التوصيل", "إغلاق رحلة التوصيل"],
  },
  {
    id: "mapping-delivery-pdf-detail-vs-primary-workflow-001",
    type: "mapping",
    domain: "services",
    service: ["delivery"],
    status: "confirmed",
    source: "know.md",
    title: "PDF details support the finalized primary Delivery workflow",
    text: "PDF-derived details support but do not override the finalized current workflow: 00 فاتورة من SAP → 01 طلب توصيل → 02 جدولة التوصيل → 03 ربط الخدمة بالسائق → 04 ملئ النموذج (سند التحميل) → 05 جاري التوصيل → 06 استلام الخدمة. The SAP invoice is the starting source, not an execution stage. Delivery appointment availability is governed by Daily Capacity, not a predefined customer booking period.",
    relatedTerms: ["دليل المستخدم", "آلية عمل خدمة التوصيل", "تفاصيل مساندة", "المسار الحالي", "00", "06", "Daily Capacity", "لا يستبدل الفلو"],
  },
]);

module.exports = {
  deliveryKnowledge,
};
