const { defineKnowledgeItems } = require("../itemFactory");

const installationKnowledge = defineKnowledgeItems([
  {
    id: "service-installation-001",
    type: "service",
    domain: "services",
    service: ["installation"],
    status: "confirmed",
    source: "know.md",
    title: "Installation service scope",
    text: "Installation is a core After-Sales service involving appointment, technician, stage, products or quantities, completion status, partial installation, remaining installation, and likely customer confirmation depending on the final flow.",
    relatedTerms: ["Installation", "خدمة التركيب", "Technician", "Appointment", "Partial Installation"],
  },
  {
    id: "workflow-installation-stage-proposed-001",
    type: "workflow",
    domain: "services",
    service: ["installation"],
    status: "proposed",
    source: "know.md",
    title: "Installation stages with partial completion",
    text: "A proposed installation stage flow is طلب تركيب to موعد to جاري التركيب to مكتمل. With partial completion, the proposed flow includes جاري التركيب to تكملة لاحقًا to موعد تكملة to جاري التركيب to مكتمل.",
    relatedTerms: ["طلب تركيب", "موعد", "جاري التركيب", "تكملة لاحقًا", "موعد تكملة", "مكتمل"],
  },
  {
    id: "requirement-installation-goods-readiness-001",
    type: "requirement",
    domain: "services",
    service: ["installation"],
    status: "requirement",
    source: "know.md",
    title: "Goods readiness before installation",
    text: "The system should check goods readiness before installation execution. If goods are incomplete, the system should handle the case as partial service instead of treating the full order as ready.",
    relatedTerms: ["Goods Ready", "جاهزية البضاعة", "Installation", "Partial Service"],
  },
  {
    id: "requirement-installation-partial-001",
    type: "requirement",
    domain: "services",
    service: ["installation"],
    status: "requirement",
    source: "know.md",
    title: "Partial installation and remaining quantity",
    text: "Installation should support partial execution, such as installing 20 meters from 30 meters and keeping 10 meters as remaining, with an option for completion later.",
    relatedTerms: ["Partial Installation", "20 متر", "30 متر", "10 متر", "تكملة لاحقًا"],
  },
  {
    id: "requirement-installation-technician-schedule-001",
    type: "business_rule",
    domain: "services",
    service: ["installation"],
    status: "requirement",
    source: "know.md",
    title: "Technician schedule conflict and buffer",
    text: "The system should prevent overlapping technician appointments and support a travel buffer; the discussed example was a 30-minute gap between appointments.",
    relatedTerms: ["Technician Conflict", "Travel Buffer", "30 دقيقة", "Appointment"],
  },
  {
    id: "open-installation-confirmation-001",
    type: "open_question",
    domain: "services",
    service: ["installation"],
    status: "unconfirmed",
    source: "know.md",
    title: "Installation customer confirmation not finalized",
    text: "Customer confirmation is mentioned as likely part of the final installation flow, but the source does not establish final confirmed behavior.",
    relatedTerms: ["Customer Confirmation", "Installation", "Unconfirmed"],
  },
]);

module.exports = {
  installationKnowledge,
};
